import os
import sys
import subprocess
import shutil
from datetime import datetime

# Root directories to exclude when scanning for CSVs
EXCLUDE_DIRS = {'.git', '.github', '.vscode', 'frontend', 'venv', 'node_modules', 'JOB_FILES', '__pycache__', 'kplc_pdfs'}

# List of scrapers from run_all_scripts.py
SCRAPERS = [
    "Accor/accor.py",
    "AcdiVoca/acdi.py",
    "AfricanUnion/au.py",
    "AgaKhan/aga.py",
    "Air/air.py",
    "Airtel/airtel.py",
    "Amazon/amazon.py",
    "BAT/bat.py",
    "BCG/bcg.py",
    "Capital/capi.py",
    "Carrefour/carre.py",
    "Clinton/clint.py",
    "Conservation/cons.py",
    "EIDU/eidu.py",
    "ERM/erm.py",
    "G4S/g4s.py",
    "GardaWorld/garda.py",
    "Glovo/glovo.py",
    "Google/google.py",
    "Heineken/hein.py",
    "IEBC/iebc.py",
    "IWG/iwg.py",
    "Irvine/ivr.py",
    "Jumia/jumia.py",
    "KOKO/koko.py",
    "KPC/kpc.py",
    "KPLC/kplc.py",
    "KenGen/kengen.py",
    "KenyaAirways/kpa.py",
    "Lesaffre/les.py",
    "Lewis/lewis.py",
    "LivingGoods/living.py",
    "MIDIS/mid.py",
    "Mckinsey/mck.py",
    "Microsoft/microsoft.py",
    "MillarCameron/milar.py",
    "NCBA/ncba.py",
    "NTT_DATA/ntt.py",
    "Natmedia/nat.py",
    "NeumannKaffee/kaffee.py",
    "NovaPioneer/nova.py",
    "Prospect33/prospect.py",
    "QONA/qona.py",
    "Reckitt/reckitt.py",
    "RoyalMedia/royal.py",
    "SAP/sap.py",
    "SIC/sic.py",
    "SNV/snv.py",
    "Seaways/sea.py",
    "Solidaridad/soli.py",
    "SunKing/sun.py",
    "TouchInspiration/touch.py",
    "UNFPA/unfpa.py",
    "absa/absa.py",
    "cloverleaf/clover.py",
    "deloitte/deloitte.py",
    "dlight/dlight.py",
    "equity/equity.py",
    "i&m-/i&m.py",
    "jotun/jotun.py",
    "kcb/kcb.py",
    "kq/kq.py",
    "kra/kra.py",
    "mastercard/master.py",
    "mkopa/mkopa.py",
    "oneacre/one.py",
    "rentokil/rento.py",
    "safaricom/safscraping.py",
    "sightsavers/sight.py",
    "standardAero/aero.py",
    "sunculture/sunc.py",
    "tala/tala.py",
    "undp/undp.py"
]

def run_scraper(script_path):
    base_dir = os.path.dirname(os.path.abspath(__file__))
    full_path = os.path.join(base_dir, script_path)
    
    if not os.path.exists(full_path):
        print(f"❌ NOT FOUND: {script_path}")
        return False, "File not found"
        
    print(f"\n🚀 Running: {script_path}")
    print("-" * 50)
    
    try:
        env = os.environ.copy()
        env["PYTHONIOENCODING"] = "utf-8"
        env["PYTHONUTF8"] = "1"
        
        result = subprocess.run(
            [sys.executable, full_path],
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=120,
            cwd=os.path.dirname(full_path),
            env=env
        )
        
        if result.returncode == 0:
            print(f"✅ SUCCESS: {script_path}")
            return True, result.stdout
        else:
            print(f"❌ FAILED: {script_path}")
            print(f"Error:\n{result.stderr}")
            return False, result.stderr
            
    except subprocess.TimeoutExpired:
        print(f"⏱️ TIMEOUT: {script_path}")
        return False, "Timeout expired"
    except Exception as e:
        print(f"❌ ERROR: {script_path} - {str(e)}")
        return False, str(e)

def harvest_csv_files():
    print("\n📦 Harvesting CSV files generated by scrapers...")
    base_dir = os.path.dirname(os.path.abspath(__file__))
    job_files_dir = os.path.join(base_dir, "JOB_FILES")
    os.makedirs(job_files_dir, exist_ok=True)
    
    copied_count = 0
    
    for root, dirs, files in os.walk(base_dir):
        # Exclude directories
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        
        for file in files:
            if file.endswith('.csv'):
                src_path = os.path.join(root, file)
                # Determine destination file name based on company/scraper
                dest_file = file
                # Standardize filenames
                if "equity" in file.lower() and "bank" not in file.lower():
                    dest_file = "equity_bank_jobs.csv"
                    
                dest_path = os.path.join(job_files_dir, dest_file)
                
                # Check if it's the exact same file in JOB_FILES/
                if os.path.abspath(src_path) == os.path.abspath(dest_path):
                    continue
                    
                try:
                    shutil.copy2(src_path, dest_path)
                    print(f"  Mapped & copied: {os.path.relpath(src_path, base_dir)} -> JOB_FILES/{dest_file}")
                    copied_count += 1
                except Exception as e:
                    print(f"  ⚠️ Error copying {file}: {e}")
                    
    print(f"✅ Finished harvesting: copied {copied_count} CSV files to JOB_FILES/")

def main():
    print("=" * 80)
    print("RUNNING SCRAPERS & UPDATING FRONTEND DATA")
    print("=" * 80)
    
    # We will run a set of major/critical scrapers to make sure we get fresh listings
    # Running all 70+ sequentially is great, but let's run a selection of primary ones first
    # or run all if we can.
    primary_scrapers = [
        "safaricom/safscraping.py",
        "absa/absa.py",
        "equity/equity.py",
        "deloitte/deloitte.py",
        "kcb/kcb.py",
        "kq/kq.py",
        "undp/undp.py",
        "tala/tala.py",
        "Accor/accor.py"
    ]
    
    failed_scrapers = []
    
    # Run primary scrapers
    for scraper in primary_scrapers:
        success, _ = run_scraper(scraper)
        if not success:
            failed_scrapers.append(scraper)
            
    # Harvest any generated CSVs across the workspace to JOB_FILES/
    harvest_csv_files()
    
    # Re-compile frontend JSON with compile_jobs.py
    print("\n🔧 Compiling jobs into frontend/public/jobs.json...")
    try:
        result = subprocess.run(
            [sys.executable, "compile_jobs.py"],
            capture_output=True,
            text=True,
            encoding="utf-8"
        )
        print(result.stdout)
    except Exception as e:
        print(f"❌ Error compiling jobs: {e}")
        
    if failed_scrapers:
        print("\n⚠️ The following scrapers failed:")
        for f in failed_scrapers:
            print(f"  - {f}")
    else:
        print("\n🎉 All primary scrapers succeeded!")

if __name__ == "__main__":
    main()
